[project]
name = "sade"
version = "0.1.0"
description = "Film selector"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bedrock-agentcore>=0.1.1",
    "contextvars>=2.4",
    "nest-asyncio>=1.6.0",
    "playwright>=1.54.0",
    "strands-agents-tools>=0.2.3",
]
